# Generated by Django 4.2.8 on 2023-12-30 10:07

import apps.manager.models.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.FileField(upload_to=apps.manager.models.file.File.get_upload_path)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('size', models.IntegerField(blank=True)),
                ('type', models.CharField(choices=[('tax', 'impot'), ('bulletin', 'bulletin'), ('bank', 'banque'), ('mutual', 'mutuelle')], max_length=100)),
                ('mimetypes', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fichier',
                'verbose_name_plural': 'fichiers',
                'ordering': ['-created_at'],
            },
        ),
    ]
