# Schduler pod for main API from back image
# ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗███╗   ███╗███████╗███╗   ██╗████████╗
# ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝████╗ ████║██╔════╝████╗  ██║╚══██╔══╝
# ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ ██╔████╔██║█████╗  ██╔██╗ ██║   ██║
# ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  ██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║
# ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║███████╗██║ ╚████║   ██║
# ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
spec:
    selector:
        matchLabels:
            app: worker
    strategy:
        type: RollingUpdate
    replicas: 1
    template:
        metadata:
            labels:
                app: worker
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: cloud.google.com/gke-nodepool
                                    operator: In
                                    values:
                                        - workers
            containers:
                - name: worker-container
                  image: ${CONTAINER_REGISTRY}/back:${DEPLOY_TAG}
                  imagePullPolicy: 'Always'
                  command: ['./entrypoint']
                  args: ['celery-start']
                  envFrom:
                      - configMapRef:
                            name: config
                      - secretRef:
                            name: secrets
                  # resources:
                  #     requests:
                  #         memory: 256Mi
                  #         cpu: '0.1'
                  #     limits:
                  #         memory: 512Mi
                  #         cpu: '0.5'
                  # resources:
                  #     requests:
                  #         memory: '500Mi'
                  #         cpu: '0.3'
                  #     limits:
                  #         memory: '1000Mi'
                  #         cpu: '0.5'
