# Generated by Django 4.2.7 on 2023-12-29 15:41

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('username', models.CharField(blank=True, max_length=254, null=True)),
                ('session_token', models.CharField(max_length=2000, null=True, unique=True)),
                ('session_token_created_at', models.DateTimeField(null=True)),
                ('auth_redirect', models.CharField(help_text='Url post login', max_length=1500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_debugging', models.BooleanField(default=False)),
                ('is_cgu_accepted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=254, null=True)),
                ('last_name', models.CharField(max_length=254, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('auth_picture', models.TextField(null=True)),
                ('google_id', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('google_token', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta', models.JSONField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='users', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
