# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Jobs/License-Scanning.gitlab-ci.yml

# Read more about this feature here: https://docs.gitlab.com/ee/user/compliance/license_compliance/index.html
#
# Configure license scanning with CI/CD variables (https://docs.gitlab.com/ee/ci/variables/index.html).
# List of available variables: https://docs.gitlab.com/ee/user/compliance/license_compliance/#available-variables

variables:
    # Setting this variable will affect all Security templates
    # (SAST, Dependency Scanning, ...)
    SECURE_ANALYZERS_PREFIX: '/security-products'

    LICENSE_MANAGEMENT_SETUP_CMD: '' # If needed, specify a command to setup your environment with a custom package manager.
    LICENSE_MANAGEMENT_VERSION: 'removed'

.license_scanning:
    image:
        name: '/license-finder:'
        entrypoint: ['']
    variables:
        LM_REPORT_VERSION: '2.1'
        SETUP_CMD: 
    allow_failure: true
    script:
        - /run.sh analyze .
    artifacts:
        reports:
            license_scanning: gl-license-scanning-report.json
    dependencies: []
    rules:
        - if:  == 'true' ||  == '1'
          when: never
        - if:  &&
               =~ /\blicense_scanning\b/
