apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fileforge-local
resources:
    - ../base
patches:
    #  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
    # ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
    # ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
    # ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
    # ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
    #  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
    - target:
          kind: ConfigMap
          name: config
      patch: |-
          - op: replace
            path: /data/DEBUG
            value: '1'
          - op: replace
            path: /data/DEV_MODE
            value: '1'
          - op: replace
            path: /data/DOMAIN
            value: fileforge.localhost

    # ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗███╗   ███╗███████╗███╗   ██╗████████╗
    # ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝████╗ ████║██╔════╝████╗  ██║╚══██╔══╝
    # ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝ ██╔████╔██║█████╗  ██╔██╗ ██║   ██║
    # ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝  ██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║
    # ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║███████╗██║ ╚████║   ██║
    # ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
    - target:
          kind: Deployment
          # all deployments in namespace
      patch: |-
          - op: replace
            path: /spec/strategy/type
            value: Recreate
          - op: replace
            path: /spec/template/spec/containers/0/imagePullPolicy
            value: Never
    - target:
          kind: Job
          # all jobs in namespace
      patch: |-
          - op: replace
            path: /spec/template/spec/containers/0/imagePullPolicy
            value: Never

    # ███████╗████████╗ ██████╗ ██████╗  █████╗  ██████╗ ███████╗
    # ██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝ ██╔════╝
    # ███████╗   ██║   ██║   ██║██████╔╝███████║██║  ███╗█████╗
    # ╚════██║   ██║   ██║   ██║██╔══██╗██╔══██║██║   ██║██╔══╝
    # ███████║   ██║   ╚██████╔╝██║  ██║██║  ██║╚██████╔╝███████╗
    # ╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
    - target:
          kind:
              PersistentVolumeClaim
              # all deployments in namespace
      patch: |-
          - op: replace
            path: /spec/storageClassName
            value: standard

    # ██╗███╗   ██╗ ██████╗ ██████╗ ███████╗███████╗███████╗
    # ██║████╗  ██║██╔════╝ ██╔══██╗██╔════╝██╔════╝██╔════╝
    # ██║██╔██╗ ██║██║  ███╗██████╔╝█████╗  ███████╗███████╗
    # ██║██║╚██╗██║██║   ██║██╔══██╗██╔══╝  ╚════██║╚════██║
    # ██║██║ ╚████║╚██████╔╝██║  ██║███████╗███████║███████║
    # ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
    - target:
          kind:
              Ingress
              # all ingresses in namespace
      patch: |-
          - op: replace
            path: /spec/rules/0/host
            value: fileforge.localhost
          - op: remove
            path: /spec/tls
