# Generated by Django 4.2.2 on 2023-07-10 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Name')),
                ('title', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Title')),
                ('tags', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Tags')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Errors')),
                ('data', models.JSONField(default=dict, verbose_name='Output data')),
                ('id_celery', models.CharField(blank=True, null=True, unique=True, verbose_name='Celery id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
