apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DATABASE_URL: postgres://postgres:postgres@database-service:5432/postgres
  REDIS_URL: redis://redis-service:6379
  DEV_MODE: 0
  DEBUG: 0
