apiVersion: v1
kind: Secret
metadata:
    name: secrets
type: Opaque

### TO SET OPAQUE SECRETS

# kubectl edit secret secrets
# add this line at the end of file
# stringData:
#     MICROSOFT_CLIENT_ID: 
#     MICROSOFT_CLIENT_ID: 
#     MICROSOFT_CLIENT_ID: 

# OR
# crank set-secret MICROSOFT_CLIENT_ID 1234567890